export const MOCK_FILM_INFO = {
   adult: false,
   backdrop_path: '/9l1eZiJHmhr5jIlthMdJN5WYoff.jpg',
   belongs_to_collection: {
      id: 448150,
      name: 'Deadpool Collection',
      poster_path: '/30c5jO7YEXuF8KiWXLg9m28GWDA.jpg',
      backdrop_path: '/hBQOWY8qWXJVFAc8yLTh1teIu43.jpg',
   },
   budget: 200000000,
   genres: [
      {
         id: 28,
         name: 'Action',
      },
      {
         id: 35,
         name: 'Comedy',
      },
      {
         id: 878,
         name: 'Science Fiction',
      },
   ],
   homepage: 'https://www.marvel.com/movies/deadpool-and-wolverine',
   id: 533535,
   imdb_id: 'tt6263850',
   origin_country: ['US'],
   original_language: 'en',
   original_title: 'Deadpool & Wolverine',
   overview:
      'A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.',
   popularity: 2250.087,
   poster_path: '/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
   production_companies: [
      {
         id: 420,
         logo_path: '/hUzeosd33nzE5MCNsZxCGEKTXaQ.png',
         name: 'Marvel Studios',
         origin_country: 'US',
      },
      {
         id: 104228,
         logo_path: '/hx0C1XcSxGgat8N62GpxoJGTkCk.png',
         name: 'Maximum Effort',
         origin_country: 'US',
      },
      {
         id: 2575,
         logo_path: '/9YJrHYlcfHtwtulkFMAies3aFEl.png',
         name: '21 Laps Entertainment',
         origin_country: 'US',
      },
      {
         id: 127928,
         logo_path: '/h0rjX5vjW5r8yEnUBStFarjcLT4.png',
         name: '20th Century Studios',
         origin_country: 'US',
      },
      {
         id: 176762,
         logo_path: null,
         name: 'Kevin Feige Productions',
         origin_country: 'US',
      },
      {
         id: 22213,
         logo_path: '/qx9K6bFWJupwde0xQDwOvXkOaL8.png',
         name: 'TSG Entertainment',
         origin_country: 'US',
      },
   ],
   production_countries: [
      {
         iso_3166_1: 'US',
         name: 'United States of America',
      },
   ],
   release_date: '2024-07-24',
   revenue: 1317173104,
   runtime: 128,
   spoken_languages: [
      {
         english_name: 'English',
         iso_639_1: 'en',
         name: 'English',
      },
   ],
   status: 'Released',
   tagline: 'Come together.',
   title: 'Deadpool & Wolverine',
   video: false,
   vote_average: 7.677,
   vote_count: 3046,
};

export const MOCK_FILM_TRAILER = {
   iso_639_1: 'en',
   iso_3166_1: 'US',
   name: 'Final Trailer',
   key: 'Idh8n5XuYIA',
   site: 'YouTube',
   size: 1080,
   type: 'Trailer',
   official: true,
   published_at: '2024-07-19T14:00:23.000Z',
   id: '669a8ad15777920d534e6606',
};

export const MOCK_FILM_LIST = {
   page: 1,
   results: [
      {
         adult: false,
         backdrop_path: '/7h6TqPB3ESmjuVbxCxAeB1c9OB1.jpg',
         genre_ids: [27, 18, 878],
         id: 933260,
         original_language: 'en',
         original_title: 'The Substance',
         overview:
            'A fading celebrity decides to use a black market drug, a cell-replicating substance that temporarily creates a younger, better version of herself.',
         popularity: 4964.05,
         poster_path: '/lqoMzCcZYEFK729d6qzt349fB4o.jpg',
         release_date: '2024-09-07',
         title: 'The Substance',
         video: false,
         vote_average: 7.4,
         vote_count: 510,
      },
      {
         adult: false,
         backdrop_path: '/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg',
         genre_ids: [28, 35, 878],
         id: 533535,
         original_language: 'en',
         original_title: 'Deadpool \u0026 Wolverine',
         overview:
            'A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.',
         popularity: 2844.462,
         poster_path: '/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
         release_date: '2024-07-24',
         title: 'Deadpool \u0026 Wolverine',
         video: false,
         vote_average: 7.713,
         vote_count: 4476,
      },
      {
         adult: false,
         backdrop_path: '/xi1VSt3DtkevUmzCx2mNlCoDe74.jpg',
         genre_ids: [35, 14, 27],
         id: 917496,
         original_language: 'en',
         original_title: 'Beetlejuice Beetlejuice',
         overview:
            "After a family tragedy, three generations of the Deetz family return home to Winter River. Still haunted by Betelgeuse, Lydia's life is turned upside down when her teenage daughter, Astrid, accidentally opens the portal to the Afterlife.",
         popularity: 1986.658,
         poster_path: '/kKgQzkUCnQmeTPkyIwHly2t6ZFI.jpg',
         release_date: '2024-09-04',
         title: 'Beetlejuice Beetlejuice',
         video: false,
         vote_average: 7.204,
         vote_count: 1289,
      },
      {
         adult: false,
         backdrop_path: '/3m0j3hCS8kMAaP9El6Vy5Lqnyft.jpg',
         genre_ids: [878, 53, 18, 27],
         id: 1125510,
         original_language: 'es',
         original_title: 'El hoyo 2',
         overview:
            'After a mysterious leader imposes his law in a brutal system of vertical cells, a new arrival battles against a dubious food distribution method.',
         popularity: 1948.952,
         poster_path: '/6lTrlqGTXiVphXW8AmyndcG1pTR.jpg',
         release_date: '2024-09-27',
         title: 'The Platform 2',
         video: false,
         vote_average: 5.7,
         vote_count: 545,
      },
      {
         adult: false,
         backdrop_path: '/v9acaWVVFdZT5yAU7J2QjwfhXyD.jpg',
         genre_ids: [16, 878, 10751],
         id: 1184918,
         original_language: 'en',
         original_title: 'The Wild Robot',
         overview:
            "After a shipwreck, an intelligent robot called Roz is stranded on an uninhabited island. To survive the harsh environment, Roz bonds with the island's animals and cares for an orphaned baby goose.",
         popularity: 2282.501,
         poster_path: '/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg',
         release_date: '2024-09-12',
         title: 'The Wild Robot',
         video: false,
         vote_average: 8.562,
         vote_count: 390,
      },
      {
         adult: false,
         backdrop_path: '/xlkclSE4aq7r3JsFIJRgs21zUew.jpg',
         genre_ids: [27, 53],
         id: 1034541,
         original_language: 'en',
         original_title: 'Terrifier 3',
         overview:
            "Five years after surviving Art the Clown's Halloween massacre, Sienna and Jonathan are still struggling to rebuild their shattered lives. As the holiday season approaches, they try to embrace the Christmas spirit and leave the horrors of the past behind. But just when they think they're safe, Art returns, determined to turn their holiday cheer into a new nightmare. The festive season quickly unravels as Art unleashes his twisted brand of terror, proving that no holiday is safe.",
         popularity: 1576.845,
         poster_path: '/l1175hgL5DoXnqeZQCcU3eZIdhX.jpg',
         release_date: '2024-10-09',
         title: 'Terrifier 3',
         video: false,
         vote_average: 7.0,
         vote_count: 57,
      },
      {
         adult: false,
         backdrop_path: '/lgkPzcOSnTvjeMnuFzozRO5HHw1.jpg',
         genre_ids: [16, 10751, 35, 28],
         id: 519182,
         original_language: 'en',
         original_title: 'Despicable Me 4',
         overview:
            'Gru and Lucy and their girls—Margo, Edith and Agnes—welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad. Gru also faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, forcing the family to go on the run.',
         popularity: 1339.874,
         poster_path: '/wWba3TaojhK7NdycRhoQpsG0FaH.jpg',
         release_date: '2024-06-20',
         title: 'Despicable Me 4',
         video: false,
         vote_average: 7.133,
         vote_count: 1977,
      },
      {
         adult: false,
         backdrop_path: '/g1z1ZvYKcmk9EnVOTYXR6vkNjkZ.jpg',
         genre_ids: [14, 27, 28],
         id: 1087822,
         original_language: 'en',
         original_title: 'Hellboy: The Crooked Man',
         overview:
            "Hellboy and a rookie BPRD agent get stranded in 1950s rural Appalachia. There, they discover a small community haunted by witches, led by a local devil with a troubling connection to Hellboy's past: the Crooked Man.",
         popularity: 1395.785,
         poster_path: '/iz2GabtToVB05gLTVSH7ZvFtsMM.jpg',
         release_date: '2024-08-29',
         title: 'Hellboy: The Crooked Man',
         video: false,
         vote_average: 4.8,
         vote_count: 112,
      },
      {
         adult: false,
         backdrop_path: '/p5ozvmdgsmbWe0H8Xk7Rc8SCwAB.jpg',
         genre_ids: [16, 10751, 12, 35, 18],
         id: 1022789,
         original_language: 'en',
         original_title: 'Inside Out 2',
         overview:
            "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
         popularity: 1122.624,
         poster_path: '/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg',
         release_date: '2024-06-11',
         title: 'Inside Out 2',
         video: false,
         vote_average: 7.6,
         vote_count: 4320,
      },
      {
         adult: false,
         backdrop_path: '/iYqSQaWDttQIQzsxg9xHyg0bttG.jpg',
         genre_ids: [878, 27, 28],
         id: 945961,
         original_language: 'en',
         original_title: 'Alien: Romulus',
         overview:
            'While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.',
         popularity: 1184.287,
         poster_path: '/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg',
         release_date: '2024-08-13',
         title: 'Alien: Romulus',
         video: false,
         vote_average: 7.209,
         vote_count: 1351,
      },
      {
         adult: false,
         backdrop_path: '/tCKWksaQI8XkAQLVou0AlGab5S6.jpg',
         genre_ids: [28, 878],
         id: 1144962,
         original_language: 'en',
         original_title: 'Transmorphers: Mech Beasts',
         overview:
            '20 years after the events of Transmorphers, a newer, more advanced species of alien robot descends on a rebuilt Earth, threatening once again to destroy the planet.',
         popularity: 905.366,
         poster_path: '/oqhaffnQqSzdLrYAQA5W4IdAoCX.jpg',
         release_date: '2023-06-09',
         title: 'Transmorphers: Mech Beasts',
         video: false,
         vote_average: 4.9,
         vote_count: 23,
      },
      {
         adult: false,
         backdrop_path: '/uVWlwJebxX0M3axXAUrryJ6w9cQ.jpg',
         genre_ids: [28, 35, 80],
         id: 507241,
         original_language: 'en',
         original_title: "The Killer's Game",
         overview:
            "When top hitman Joe Flood is diagnosed with a terminal illness, he decides to take matters into his own hands – by taking a hit out on himself. But when the very hitmen he hired also target his ex-girlfriend, he must fend off an army of assassin colleagues and win back the love of his life before it's too late.",
         popularity: 925.221,
         poster_path: '/4bKlTeOUr5AKrLky8mwWvlQqyVd.jpg',
         release_date: '2024-09-12',
         title: "The Killer's Game",
         video: false,
         vote_average: 6.3,
         vote_count: 60,
      },
      {
         adult: false,
         backdrop_path: '/Asg2UUwipAdE87MxtJy7SQo08XI.jpg',
         genre_ids: [28, 14, 27],
         id: 957452,
         original_language: 'en',
         original_title: 'The Crow',
         overview:
            'Soulmates Eric and Shelly are brutally murdered when the demons of her dark past catch up with them. Given the chance to save his true love by sacrificing himself, Eric sets out to seek merciless revenge on their killers, traversing the worlds of the living and the dead to put the wrong things right.',
         popularity: 808.2,
         poster_path: '/58QT4cPJ2u2TqWZkterDq9q4yxQ.jpg',
         release_date: '2024-08-21',
         title: 'The Crow',
         video: false,
         vote_average: 5.742,
         vote_count: 610,
      },
      {
         adult: false,
         backdrop_path: '/vGaBqgY8YRzQVUbBMPnd5SmYvL7.jpg',
         genre_ids: [16, 35],
         id: 1329336,
         original_language: 'en',
         original_title: 'The Bad Guys: Haunted Heist',
         overview:
            'The crafty Bad Guys crew embarks on a high-stakes Halloween heist to swipe a priceless amulet from a spooky mansion. What could go wrong?',
         popularity: 699.477,
         poster_path: '/oEJC05CqPugMxC4rFu9r6r6vg6m.jpg',
         release_date: '2024-10-02',
         title: 'The Bad Guys: Haunted Heist',
         video: false,
         vote_average: 7.4,
         vote_count: 47,
      },
      {
         adult: false,
         backdrop_path: '/hPIWQT70wQK6akqfLXByEvr62u0.jpg',
         genre_ids: [28, 53, 27, 878],
         id: 726139,
         original_language: 'ko',
         original_title: '탈출: 프로젝트 사일런스',
         overview:
            'Due to sudden deteriorating weather conditions, visibility on the Airport Bridge is severely impaired, leaving people stranded and at risk of the bridge collapsing due to a series of chain collisions and explosions. Amidst the chaos, the canine subjects "Echo" from the military experiment "Project Silence," who were being transported in secret, break free, and all human survivors become targets of relentless attacks.',
         popularity: 921.452,
         poster_path: '/fttoFfKikQMwIoV3UVvlCvBhbUw.jpg',
         release_date: '2024-07-11',
         title: 'Project Silence',
         video: false,
         vote_average: 7.1,
         vote_count: 171,
      },
      {
         adult: false,
         backdrop_path: '/eXQ8O0ykuEB8dUJhq2WJll4vXmA.jpg',
         genre_ids: [28, 35, 80],
         id: 1210794,
         original_language: 'sv',
         original_title: 'Strul',
         overview:
            'Wrongfully convicted of murder, a clumsy electronics salesman faces police corruption and criminal conspiracies in an attempt to prove his innocence.',
         popularity: 722.163,
         poster_path: '/ildbg7ho14EHbt1fZWAkgqIyPqy.jpg',
         release_date: '2024-10-02',
         title: 'Trouble',
         video: false,
         vote_average: 7.1,
         vote_count: 78,
      },
      {
         adult: false,
         backdrop_path: '/6n8x85cljOfJkUvPDc7tTmGPv7F.jpg',
         genre_ids: [28, 27, 53],
         id: 1029235,
         original_language: 'en',
         original_title: 'Azrael',
         overview:
            'In a world where no one speaks, a devout female hunts down a young woman who has escaped her imprisonment. Recaptured by its ruthless leaders, Azrael is due to be sacrificed to pacify an ancient evil deep within the surrounding wilderness.',
         popularity: 1260.015,
         poster_path: '/qpdFKDvJS7oLKTcBLXOaMwUESbs.jpg',
         release_date: '2024-09-27',
         title: 'Azrael',
         video: false,
         vote_average: 5.6,
         vote_count: 42,
      },
      {
         adult: false,
         backdrop_path: '/cRdA9xjHBbobw4LJFsQ3j1CgpVq.jpg',
         genre_ids: [27, 53],
         id: 663712,
         original_language: 'en',
         original_title: 'Terrifier 2',
         overview:
            "A year after the Miles County massacre, Art the Clown is resurrected by a sinister entity. Art returns home, where he must hunt down and destroy teenage Sienna and her younger brother Jonathan on Halloween. As the body count rises, the siblings fight to stay alive while uncovering the true nature of Art's evil intent.",
         popularity: 682.189,
         poster_path: '/8gLhu8UFPZfH2Hv11JhTZkb9CVl.jpg',
         release_date: '2022-10-06',
         title: 'Terrifier 2',
         video: false,
         vote_average: 6.779,
         vote_count: 1815,
      },
      {
         adult: false,
         backdrop_path: '/tncbMvfV0V07UZozXdBEq4Wu9HH.jpg',
         genre_ids: [28, 80, 53, 35],
         id: 573435,
         original_language: 'en',
         original_title: 'Bad Boys: Ride or Die',
         overview:
            'After their late former Captain is framed, Lowrey and Burnett try to clear his name, only to end up on the run themselves.',
         popularity: 679.479,
         poster_path: '/oGythE98MYleE6mZlGs5oBGkux1.jpg',
         release_date: '2024-06-05',
         title: 'Bad Boys: Ride or Die',
         video: false,
         vote_average: 7.514,
         vote_count: 2180,
      },
      {
         adult: false,
         backdrop_path: '/zAqBIeO71BFL7bAtP5TFzVjVamy.jpg',
         genre_ids: [10749, 18],
         id: 1079091,
         original_language: 'en',
         original_title: 'It Ends with Us',
         overview:
            "When a woman's first love suddenly reenters her life, her relationship with a charming, but abusive neurosurgeon is upended, and she realizes she must learn to rely on her own strength to make an impossible choice for her future.",
         popularity: 670.41,
         poster_path: '/AjV6jFJ2YFIluYo4GQf13AA1tqu.jpg',
         release_date: '2024-08-07',
         title: 'It Ends with Us',
         video: false,
         vote_average: 7.127,
         vote_count: 800,
      },
   ],
   total_pages: 46544,
   total_results: 930880,
};

export const MOCK_SERIES_LIST = {
   page: 1,
   results: [
      {
         adult: false,
         backdrop_path: '/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg',
         genre_ids: [10765, 18, 10759],
         id: 1399,
         origin_country: ['US'],
         original_language: 'en',
         original_name: 'Game of Thrones',
         overview:
            'Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north.',
         popularity: 1242.503,
         poster_path: '/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg',
         first_air_date: '2011-04-17',
         name: 'Game of Thrones',
         vote_average: 8.456,
         vote_count: 24680,
      },
      {
         adult: false,
         backdrop_path: '/9faGSFi5jam6pDWGNd0p8JcJgXQ.jpg',
         genre_ids: [18, 80],
         id: 1396,
         origin_country: ['US'],
         original_language: 'en',
         original_name: 'Breaking Bad',
         overview:
            "Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
         popularity: 612.211,
         poster_path: '/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg',
         first_air_date: '2008-01-20',
         name: 'Breaking Bad',
         vote_average: 8.921,
         vote_count: 15222,
      },
      {
         adult: false,
         backdrop_path: null,
         genre_ids: [35],
         id: 999001,
         origin_country: ['US'],
         original_language: 'en',
         original_name: 'Unaired Pilot',
         overview: 'A series with no air date yet.',
         popularity: 1.2,
         poster_path: null,
         name: 'Unaired Pilot',
         vote_average: 0,
         vote_count: 0,
      },
   ],
   total_pages: 10,
   total_results: 200,
};

export const MOCK_SERIES_INFO = {
   adult: false,
   backdrop_path: '/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg',
   created_by: [
      {
         id: 9813,
         credit_id: '5256c8c219c2956ff604858a',
         name: 'David Benioff',
         gender: 2,
         profile_path: '/xvNN5huL0X8yJ7h3IZfGG4O2zBD.jpg',
      },
      {
         id: 228068,
         credit_id: '552e611e9251413fea000901',
         name: 'D. B. Weiss',
         gender: 2,
         profile_path: '/2RMejaT793U9KRk2IEbFfteQntE.jpg',
      },
   ],
   episode_run_time: [60],
   first_air_date: '2011-04-17',
   genres: [
      { id: 10765, name: 'Sci-Fi & Fantasy' },
      { id: 18, name: 'Drama' },
      { id: 10759, name: 'Action & Adventure' },
   ],
   homepage: 'https://www.hbo.com/game-of-thrones',
   id: 1399,
   in_production: false,
   languages: ['en'],
   last_air_date: '2019-05-19',
   name: 'Game of Thrones',
   networks: [
      {
         id: 49,
         logo_path: '/tuomPhY2UtuPTqqFnKMVHvSb724.png',
         name: 'HBO',
         origin_country: 'US',
      },
   ],
   number_of_episodes: 73,
   number_of_seasons: 8,
   origin_country: ['US'],
   original_language: 'en',
   original_name: 'Game of Thrones',
   overview:
      'Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north.',
   popularity: 1242.503,
   poster_path: '/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg',
   production_companies: [
      {
         id: 76043,
         logo_path: '/9RO2vbQ67otPrBLXCaC8UMp3Qat.png',
         name: 'Revolution Sun Studios',
         origin_country: 'US',
      },
   ],
   seasons: [
      {
         air_date: '2010-12-05',
         episode_count: 285,
         id: 3627,
         name: 'Specials',
         overview: '',
         poster_path: '/kMTcwNRfFKCZ0O2OaBZS0nZ2AIe.jpg',
         season_number: 0,
         vote_average: 0,
      },
      {
         air_date: '2011-04-17',
         episode_count: 10,
         id: 3624,
         name: 'Season 1',
         overview: 'Trouble is brewing in the Seven Kingdoms of Westeros.',
         poster_path: '/wgfKiqzuMrFIkU1M68DDDY8kGC1.jpg',
         season_number: 1,
         vote_average: 8.3,
      },
      {
         air_date: '2019-04-14',
         episode_count: 6,
         id: 107971,
         name: 'Season 8',
         overview: 'The Great War has come.',
         poster_path: null,
         season_number: 8,
         vote_average: 6.6,
      },
   ],
   spoken_languages: [
      { english_name: 'English', iso_639_1: 'en', name: 'English' },
   ],
   status: 'Ended',
   tagline: 'Winter is coming.',
   type: 'Scripted',
   vote_average: 8.456,
   vote_count: 24680,
   external_ids: {
      imdb_id: 'tt0944947',
      freebase_mid: '/m/0524b41',
      tvdb_id: 121361,
   },
};

export const MOCK_SERIES_CREDITS = {
   cast: [
      {
         adult: false,
         gender: 1,
         id: 1223786,
         known_for_department: 'Acting',
         name: 'Emilia Clarke',
         original_name: 'Emilia Clarke',
         popularity: 45.1,
         profile_path: '/86jeYFV3Ov69UmJ3bBrE1nKJlN4.jpg',
         character: 'Daenerys Targaryen',
         credit_id: '5256c8af19c2956ff6047af5',
         order: 0,
      },
      {
         adult: false,
         gender: 2,
         id: 22970,
         known_for_department: 'Acting',
         name: 'Peter Dinklage',
         original_name: 'Peter Dinklage',
         popularity: 30.2,
         profile_path: null,
         character: 'Tyrion Lannister',
         credit_id: '5256c8b419c2956ff6047cd8',
         order: 1,
      },
   ],
   crew: [
      {
         adult: false,
         gender: 2,
         id: 9813,
         known_for_department: 'Writing',
         name: 'David Benioff',
         original_name: 'David Benioff',
         popularity: 5.5,
         profile_path: '/xvNN5huL0X8yJ7h3IZfGG4O2zBD.jpg',
         credit_id: '5256c8c219c2956ff604858a',
         department: 'Production',
         job: 'Executive Producer',
      },
   ],
   id: 1399,
};

export const MOCK_FILM_CREDITS = {
   id: 533535,
   cast: [
      {
         adult: false,
         gender: 2,
         id: 10859,
         known_for_department: 'Acting',
         name: 'Ryan Reynolds',
         original_name: 'Ryan Reynolds',
         popularity: 120.4,
         profile_path: '/algQ1VEno2W9SesoArWcZTeF617.jpg',
         character: 'Wade Wilson / Deadpool',
         credit_id: '5d3c9a0d3d9d2d0011b3c1c6',
         order: 0,
      },
      {
         adult: false,
         gender: 2,
         id: 6968,
         known_for_department: 'Acting',
         name: 'Hugh Jackman',
         original_name: 'Hugh Jackman',
         popularity: 95.7,
         profile_path: null,
         character: 'Logan / Wolverine',
         credit_id: '6339a2a8f7e6b9007a8a1a0e',
         order: 1,
      },
   ],
   crew: [
      {
         adult: false,
         gender: 2,
         id: 12891,
         known_for_department: 'Directing',
         name: 'Shawn Levy',
         original_name: 'Shawn Levy',
         popularity: 12.3,
         profile_path: null,
         credit_id: '6426b4a8d5b4d7007d5c1d7f',
         department: 'Directing',
         job: 'Director',
      },
      {
         adult: false,
         gender: 2,
         id: 1178938,
         known_for_department: 'Writing',
         name: 'Rhett Reese',
         original_name: 'Rhett Reese',
         popularity: 4.1,
         profile_path: null,
         credit_id: '6426b4c0d5b4d7007d5c1d9a',
         department: 'Writing',
         job: 'Screenplay',
      },
   ],
};

export const MOCK_SERIES_RECOMMENDATIONS = {
   page: 1,
   results: [
      {
         backdrop_path: '/9faGSFi5jam6pDWGNd0p8JcJgXQ.jpg',
         id: 1396,
         name: 'Breaking Bad',
         original_name: 'Breaking Bad',
         overview: 'Chemistry teacher turns to crime.',
         poster_path: '/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg',
         media_type: 'tv',
         adult: false,
         original_language: 'en',
         genre_ids: [18, 80],
         popularity: 612.211,
         first_air_date: '2008-01-20',
         vote_average: 8.921,
         vote_count: 15222,
         origin_country: ['US'],
      },
   ],
   total_pages: 1,
   total_results: 1,
};

export const MOCK_RELEASE_DATES = {
   id: 533535,
   results: [
      {
         iso_3166_1: 'GB',
         release_dates: [
            {
               certification: '15',
               descriptors: [],
               iso_639_1: '',
               note: '',
               release_date: '2024-07-25T00:00:00.000Z',
               type: 3,
            },
         ],
      },
      {
         iso_3166_1: 'US',
         release_dates: [
            {
               certification: '',
               descriptors: [],
               iso_639_1: '',
               note: 'New York City, New York',
               release_date: '2024-07-22T00:00:00.000Z',
               type: 1,
            },
            {
               certification: 'R',
               descriptors: [],
               iso_639_1: '',
               note: '',
               release_date: '2024-07-26T00:00:00.000Z',
               type: 3,
            },
            {
               certification: 'R',
               descriptors: [],
               iso_639_1: '',
               note: '',
               release_date: '2024-10-01T00:00:00.000Z',
               type: 4,
            },
         ],
      },
      {
         iso_3166_1: 'ES',
         release_dates: [
            {
               certification: '16',
               descriptors: [],
               iso_639_1: 'es',
               note: '',
               release_date: '2024-07-24T00:00:00.000Z',
               type: 3,
            },
         ],
      },
      {
         iso_3166_1: 'FR',
         release_dates: [
            {
               certification: '',
               descriptors: [],
               iso_639_1: '',
               note: '',
               release_date: '2024-07-24T00:00:00.000Z',
               type: 3,
            },
         ],
      },
   ],
};

export const MOCK_GENRES = {
   genres: [
      { id: 28, name: 'Action' },
      { id: 18, name: 'Drama' },
      { id: 878, name: 'Science Fiction' },
   ],
};

export const MOCK_DISCOVER_MOVIES = {
   page: 2,
   total_pages: 812,
   total_results: 16231,
   results: MOCK_FILM_LIST.results.slice(0, 4),
};

export const MOCK_SEASON_DETAIL = {
   _id: '5256c89f19c2956ff6046d47',
   air_date: '2011-04-17',
   episodes: [
      {
         air_date: '2011-04-17',
         episode_number: 1,
         episode_type: 'standard',
         id: 63056,
         name: 'Winter Is Coming',
         overview:
            "Jon Arryn, the Hand of the King, is dead. King Robert Baratheon plans to ask his oldest friend, Eddard Stark, to take Jon's place. Across the sea, Viserys Targaryen plans to wed his sister to a nomadic warlord in exchange for an army.",
         production_code: '101',
         runtime: 62,
         season_number: 1,
         show_id: 1399,
         still_path: '/9hGF3WUkBf7cSjMg0cdMDHJkByd.jpg',
         vote_average: 8.1,
         vote_count: 380,
      },
      {
         air_date: '2011-04-24',
         episode_number: 2,
         episode_type: 'standard',
         id: 63057,
         name: 'The Kingsroad',
         overview:
            'While Bran recovers from his fall, Ned takes only his daughters to King’s Landing. Jon Snow goes with his uncle Benjen to the Wall. Tyrion joins them.',
         production_code: '102',
         runtime: 56,
         season_number: 1,
         show_id: 1399,
         still_path: null,
         vote_average: 7.9,
         vote_count: 290,
      },
      {
         air_date: null,
         episode_number: 3,
         episode_type: 'standard',
         id: 63058,
         name: 'Lord Snow',
         overview: '',
         production_code: '103',
         runtime: null,
         season_number: 1,
         show_id: 1399,
         still_path: null,
         vote_average: 0,
         vote_count: 0,
      },
   ],
   name: 'Season 1',
   overview:
      'Trouble is brewing in the Seven Kingdoms of Westeros. For the driven inhabitants of this visionary world, control of Westeros’ Iron Throne holds the lure of great power.',
   id: 3624,
   poster_path: '/wgfKiqzuMrFIkU1M68DDDY8kGC1.jpg',
   season_number: 1,
   vote_average: 8.3,
};

export const MOCK_PERSON_INFO = {
   adult: false,
   also_known_as: ['Emilia Isobel Euphemia Rose Clarke', 'Milly'],
   biography:
      'Emilia Isobel Euphemia Rose Clarke (born 23 October 1986) is an English actress. She is best known for her role as Daenerys Targaryen in the HBO series Game of Thrones (2011–2019).',
   birthday: '1986-10-23',
   deathday: null,
   gender: 1,
   homepage: null,
   id: 1223786,
   imdb_id: 'nm3592338',
   known_for_department: 'Acting',
   name: 'Emilia Clarke',
   place_of_birth: 'London, England, UK',
   popularity: 45.1,
   profile_path: '/86jeYFV3Ov69UmJ3bBrE1nKJlN4.jpg',
   external_ids: {
      imdb_id: 'nm3592338',
      instagram_id: 'emilia_clarke',
   },
   combined_credits: {
      cast: [
         {
            adult: false,
            backdrop_path: '/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg',
            genre_ids: [10765, 18],
            id: 1399,
            origin_country: ['US'],
            original_language: 'en',
            original_name: 'Game of Thrones',
            overview: 'Seven noble families fight for control of Westeros.',
            popularity: 1242.503,
            poster_path: '/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg',
            first_air_date: '2011-04-17',
            name: 'Game of Thrones',
            vote_average: 8.456,
            vote_count: 24680,
            character: 'Daenerys Targaryen',
            credit_id: '5256c8af19c2956ff6047af5',
            episode_count: 73,
            media_type: 'tv',
         },
         {
            adult: false,
            backdrop_path: '/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg',
            genre_ids: [10765, 18],
            id: 1399,
            origin_country: ['US'],
            original_language: 'en',
            original_name: 'Game of Thrones',
            overview: 'Seven noble families fight for control of Westeros.',
            popularity: 1242.503,
            poster_path: '/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg',
            first_air_date: '2011-04-17',
            name: 'Game of Thrones',
            vote_average: 8.456,
            vote_count: 24680,
            character: 'Self',
            credit_id: '5b4d8c4f0e0a2617b1000f2c',
            episode_count: 2,
            media_type: 'tv',
         },
         {
            adult: false,
            backdrop_path: '/8I37NtDffNV7AZlDa7uDvvqhovU.jpg',
            genre_ids: [28, 12, 878],
            id: 348350,
            original_language: 'en',
            original_title: 'Solo: A Star Wars Story',
            overview: 'Han Solo and Chewbacca.',
            popularity: 60.2,
            poster_path: '/4oD6VEccFkorEBTEDXtpLAaz0Rl.jpg',
            release_date: '2018-05-15',
            title: 'Solo: A Star Wars Story',
            video: false,
            vote_average: 6.6,
            vote_count: 7800,
            character: "Qi'ra",
            credit_id: '58a8a1d4c3a3684d5e00d1c0',
            order: 2,
            media_type: 'movie',
         },
         {
            adult: false,
            backdrop_path: null,
            genre_ids: [18],
            id: 999002,
            original_language: 'en',
            original_title: 'Unreleased Drama',
            overview: '',
            popularity: 1.1,
            poster_path: null,
            release_date: '',
            title: 'Unreleased Drama',
            video: false,
            vote_average: 0,
            vote_count: 0,
            character: 'Lead',
            credit_id: '6a1b2c3d4e5f60718293a4b5',
            order: 0,
            media_type: 'movie',
         },
      ],
      crew: [
         {
            adult: false,
            backdrop_path: null,
            genre_ids: [99],
            id: 654321,
            original_language: 'en',
            original_title: 'Behind the Throne',
            overview: 'A documentary.',
            popularity: 3.4,
            poster_path: null,
            release_date: '2020-02-02',
            title: 'Behind the Throne',
            video: false,
            vote_average: 7.0,
            vote_count: 12,
            credit_id: '5e3a1b2c3d4e5f6071829a0b',
            department: 'Production',
            job: 'Executive Producer',
            media_type: 'movie',
         },
      ],
   },
};

/** Shape of `/movie/{id}/images` and `/tv/{id}/images`. Deliberately unsorted. */
export const MOCK_MEDIA_IMAGES = {
   id: 533535,
   backdrops: [
      {
         aspect_ratio: 1.778,
         height: 1080,
         iso_639_1: null,
         file_path: '/backdrop-mid.jpg',
         vote_average: 5.3,
         vote_count: 4,
         width: 1920,
      },
      {
         aspect_ratio: 1.778,
         height: 2160,
         iso_639_1: 'en',
         file_path: '/backdrop-top.jpg',
         vote_average: 5.8,
         vote_count: 10,
         width: 3840,
      },
      {
         aspect_ratio: 1.778,
         height: 720,
         iso_639_1: null,
         file_path: '/backdrop-low.jpg',
         vote_average: 5.3,
         vote_count: 2,
         width: 1280,
      },
   ],
   logos: [],
   posters: [
      {
         aspect_ratio: 0.667,
         height: 3000,
         iso_639_1: 'en',
         file_path: '/poster.jpg',
         vote_average: 6.1,
         vote_count: 8,
         width: 2000,
      },
   ],
};

/**
 * Shape of `/movie/{id}/reviews` and `/tv/{id}/reviews`. Oldest first, as TMDB
 * returns them. Covers all three avatar formats and a missing rating.
 */
export const MOCK_REVIEWS = {
   id: 533535,
   page: 1,
   results: [
      {
         author: 'oldtimer',
         author_details: {
            name: '',
            username: 'oldtimer',
            avatar_path:
               '/https://secure.gravatar.com/avatar/0123456789abcdef0123456789abcdef.jpg',
            rating: 6,
         },
         content: 'Short and sweet. Worth a watch.',
         created_at: '2024-07-25T10:00:00.000Z',
         id: 'review-oldest',
         updated_at: '2024-07-25T10:00:00.000Z',
         url: 'https://www.themoviedb.org/review/review-oldest',
      },
      {
         author: 'CinemaSerf',
         author_details: {
            name: 'Cinema Serf',
            username: 'CinemaSerf',
            avatar_path: '/yz2HPme8NPLne0mM8tBnZ5ZWJzf.jpg',
            rating: null,
         },
         content:
            'Paragraph one of a long review that goes on for quite a while, discussing the plot, the performances, the direction and the score in enough detail to need clamping on the page.\n\nParagraph two continues in the same vein and adds a few more observations about pacing and tone.\n\nParagraph three wraps things up with a verdict and a recommendation for who might enjoy it most.',
         created_at: '2024-07-27T09:30:00.000Z',
         id: 'review-long',
         updated_at: '2024-07-28T11:00:00.000Z',
         url: 'https://www.themoviedb.org/review/review-long',
      },
      {
         author: 'newcomer',
         author_details: {
            name: 'New Comer',
            username: 'newcomer',
            avatar_path: null,
            rating: 9.5,
         },
         content: 'Loved it. Best of the year so far.',
         created_at: '2024-08-01T18:45:00.000Z',
         id: 'review-newest',
         updated_at: '2024-08-01T18:45:00.000Z',
         url: 'https://www.themoviedb.org/review/review-newest',
      },
   ],
   total_pages: 1,
   total_results: 3,
};

/** `/search/multi?query=severance`: a series, a film and a person. */
export const MOCK_MULTI_SEARCH = {
   page: 1,
   results: [
      {
         adult: false,
         backdrop_path: '/1XcXCNaMExW3CYKe9ijz6f0BMTv.jpg',
         genre_ids: [18, 9648, 878],
         id: 95396,
         media_type: 'tv',
         name: 'Severance',
         origin_country: ['US'],
         original_language: 'en',
         original_name: 'Severance',
         overview:
            'Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives.',
         popularity: 96.36,
         poster_path: '/pPHpeI2X1qEd1CS1SeyrdhZ4qnT.jpg',
         first_air_date: '2022-02-17',
         vote_average: 8.4,
         vote_count: 2900,
      },
      {
         adult: false,
         backdrop_path: '/kUxVQ1rSgL3hqO5f8wUeInW6bY9.jpg',
         genre_ids: [27, 35],
         id: 5072,
         media_type: 'movie',
         original_language: 'en',
         original_title: 'Severance',
         overview:
            'A team-building weekend in the mountains of Eastern Europe goes horribly wrong for the sales division of an arms company.',
         popularity: 8.2,
         poster_path: '/4c7qqP0pMxHDX2rQtJfBnCzVZBk.jpg',
         release_date: '2006-08-25',
         title: 'Severance',
         video: false,
         vote_average: 6.2,
         vote_count: 520,
      },
      {
         adult: false,
         gender: 1,
         id: 18891,
         known_for: [],
         known_for_department: 'Acting',
         media_type: 'person',
         name: 'Joan Severance',
         original_name: 'Joan Severance',
         popularity: 4.1,
         profile_path: '/xyz.jpg',
      },
   ],
   total_pages: 1,
   total_results: 3,
};

/** `/search/keyword?query=time%20tra`. */
export const MOCK_KEYWORDS = {
   page: 1,
   results: [
      { id: 285095, name: 'time trial' },
      { id: 4379, name: 'time travel' },
      { id: 382031, name: 'time-traveling gang' },
   ],
   total_pages: 1,
   total_results: 3,
};
