/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UpcomingIndexRouteImport } from './routes/upcoming/index'
import { Route as TopRatedIndexRouteImport } from './routes/top-rated/index'
import { Route as PopularIndexRouteImport } from './routes/popular/index'
import { Route as FavoritesIndexRouteImport } from './routes/favorites/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as FilmFilmIdRouteImport } from './routes/film/$filmId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpcomingIndexRoute = UpcomingIndexRouteImport.update({
  id: '/upcoming/',
  path: '/upcoming/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopRatedIndexRoute = TopRatedIndexRouteImport.update({
  id: '/top-rated/',
  path: '/top-rated/',
  getParentRoute: () => rootRouteImport,
} as any)
const PopularIndexRoute = PopularIndexRouteImport.update({
  id: '/popular/',
  path: '/popular/',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesIndexRoute = FavoritesIndexRouteImport.update({
  id: '/favorites/',
  path: '/favorites/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmFilmIdRoute = FilmFilmIdRouteImport.update({
  id: '/film/$filmId',
  path: '/film/$filmId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/film/$filmId.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/film/$filmId': typeof FilmFilmIdRoute
  '/about/': typeof AboutIndexRoute
  '/favorites/': typeof FavoritesIndexRoute
  '/popular/': typeof PopularIndexRoute
  '/top-rated/': typeof TopRatedIndexRoute
  '/upcoming/': typeof UpcomingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/film/$filmId': typeof FilmFilmIdRoute
  '/about': typeof AboutIndexRoute
  '/favorites': typeof FavoritesIndexRoute
  '/popular': typeof PopularIndexRoute
  '/top-rated': typeof TopRatedIndexRoute
  '/upcoming': typeof UpcomingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/film/$filmId': typeof FilmFilmIdRoute
  '/about/': typeof AboutIndexRoute
  '/favorites/': typeof FavoritesIndexRoute
  '/popular/': typeof PopularIndexRoute
  '/top-rated/': typeof TopRatedIndexRoute
  '/upcoming/': typeof UpcomingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/film/$filmId'
    | '/about/'
    | '/favorites/'
    | '/popular/'
    | '/top-rated/'
    | '/upcoming/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/film/$filmId'
    | '/about'
    | '/favorites'
    | '/popular'
    | '/top-rated'
    | '/upcoming'
  id:
    | '__root__'
    | '/'
    | '/film/$filmId'
    | '/about/'
    | '/favorites/'
    | '/popular/'
    | '/top-rated/'
    | '/upcoming/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FilmFilmIdRoute: typeof FilmFilmIdRoute
  AboutIndexRoute: typeof AboutIndexRoute
  FavoritesIndexRoute: typeof FavoritesIndexRoute
  PopularIndexRoute: typeof PopularIndexRoute
  TopRatedIndexRoute: typeof TopRatedIndexRoute
  UpcomingIndexRoute: typeof UpcomingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upcoming/': {
      id: '/upcoming/'
      path: '/upcoming'
      fullPath: '/upcoming/'
      preLoaderRoute: typeof UpcomingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-rated/': {
      id: '/top-rated/'
      path: '/top-rated'
      fullPath: '/top-rated/'
      preLoaderRoute: typeof TopRatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/popular/': {
      id: '/popular/'
      path: '/popular'
      fullPath: '/popular/'
      preLoaderRoute: typeof PopularIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites/': {
      id: '/favorites/'
      path: '/favorites'
      fullPath: '/favorites/'
      preLoaderRoute: typeof FavoritesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/film/$filmId': {
      id: '/film/$filmId'
      path: '/film/$filmId'
      fullPath: '/film/$filmId'
      preLoaderRoute: typeof FilmFilmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FilmFilmIdRoute: FilmFilmIdRoute,
  AboutIndexRoute: AboutIndexRoute,
  FavoritesIndexRoute: FavoritesIndexRoute,
  PopularIndexRoute: PopularIndexRoute,
  TopRatedIndexRoute: TopRatedIndexRoute,
  UpcomingIndexRoute: UpcomingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
